Repository Howmies/howmies-api, pull requests merged in 2020-04, with the labels that each got.

#47 ch(refactor): implement central login handler [Starts #46]
  app.js
  controllers/FacebookLogin.js
  controllers/PostImages.js
  controllers/PostProperty.js
  controllers/RefreshToken.js
  controllers/UserLogin.js
  controllers/UserSignup.js
  middleware/LoginHandler.js
  middleware/configs/elephantsql.js
  middleware/configs/facebookConfig.js
  routes/FacebookLogin.js
  spec/PostPropertySpec.js
  spec/userSignupSpec.js
Labels: chore

#48 Ft facebook login #41
  app.js
  controllers/FacebookLogin.js
  controllers/PostImages.js
  controllers/PostProperty.js
  controllers/RefreshToken.js
  controllers/UserLogin.js
  controllers/UserSignup.js
  middleware/LoginHandler.js
  middleware/configs/elephantsql.js
  middleware/configs/facebookConfig.js
  middleware/request_validator/FacebookLogin.js
  package-lock.json
  package.json
  routes/FacebookLogin.js
  spec/PostPropertySpec.js
  spec/userSignupSpec.js
Labels: enhancement

#50 ft(CORS):add and implement CORS [Finished #49]
  app.js
  package-lock.json
  package.json
Labels: enhancement

#45 Ft user signout #39
  app.js
  controllers/UserSignout.js
  routes/UserSignout.js
Labels: enhancement

#52 bug(user-signout): esql config in UserSignout.js [Finishes #51]
  controllers/UserSignout.js
Labels: bug

#55 bug(env-err): removed env condition [Finishes #54]
  .gitignore
  controllers/PostImages.js
Labels: bug

#59 (travis-heroku) add heroku api securekey to env [Fixes #22]
  .travis.yml
Labels: chore

#60 (travis-heroku) change heroku api secure key env name [Fixes #22]
  .travis.yml
Labels: chore
